apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.json
  - 10-stable-service.json
  - 11-canary-service.json
  - 12-route.json
  - 13-analysis-template.json
  - 20-rollout.json
  - 30-servicemonitor.json
